# Generated by Django 5.0.6 on 2024-11-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='static_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
