# Generated by Django 5.0.6 on 2024-12-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_customuser_static_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSMS',
            fields=[
                ('massage_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'checksms',
                'indexes': [models.Index(fields=['phone_number', 'massage_id'], name='checksms_phone_n_80b0f6_idx')],
            },
        ),
    ]
