# Generated by Django 5.0.6 on 2024-12-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_checksms'),
    ]

    operations = [
        migrations.AddField(
            model_name='checksms',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
