# Generated by Django 5.0.6 on 2024-12-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_checksms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='post_index',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
