# Generated by Django 5.0.6 on 2024-11-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('services_id', models.ManyToManyField(blank=True, related_name='category_services', to='db_models.services')),
            ],
            options={
                'db_table': 'category_services',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='category_se_id_afe094_idx')],
            },
        ),
    ]
