# Generated by Django 5.0.6 on 2024-12-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0005_alter_categoryfaq_faq_id_alter_marks_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='count_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
