<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-12-08 05:05

=======
# Generated by Django 5.0.6 on 2024-12-09 16:24

import django.db.models.deletion
from django.conf import settings
>>>>>>> 2d32d04 (full complated uzpost backend)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 2d32d04 (full complated uzpost backend)
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='PostalOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ems_international_post', models.CharField(blank=True, max_length=255, null=True)),
                ('one_step', models.CharField(blank=True, max_length=255, null=True)),
                ('index', models.CharField(max_length=20)),
                ('geolocation', models.URLField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('name_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('mfy', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.CharField(blank=True, max_length=50, null=True)),
                ('apartment', models.CharField(blank=True, max_length=50, null=True)),
                ('working_days', models.CharField(max_length=255)),
                ('working_days_2', models.CharField(blank=True, max_length=255, null=True)),
                ('working_hours', models.CharField(max_length=255)),
                ('working_hours_2', models.CharField(blank=True, max_length=255, null=True)),
                ('weekend_days', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'postaloffice',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='postaloffic_id_7adcbf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=255)),
                ('warehouse_lat', models.FloatField()),
                ('warehouse_lon', models.FloatField()),
                ('city_id', models.IntegerField()),
                ('city_name', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=100)),
                ('region_name', models.CharField(max_length=100)),
                ('index', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'warehouse',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id'], name='warehouse_id_04894e_idx')],
=======
            name='OrderCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('barcode', models.CharField(max_length=400)),
                ('fromjurisdiction', models.CharField(max_length=500)),
                ('tojurisdiction', models.CharField(max_length=500)),
                ('from_phone_number', models.CharField(max_length=100)),
                ('to_phone_number', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=250)),
                ('from_country_code', models.CharField(max_length=400)),
                ('to_country_code', models.CharField(max_length=400)),
                ('price', models.FloatField()),
                ('price_code', models.CharField(max_length=400)),
                ('payment_type', models.CharField(max_length=400)),
                ('shipment_type', models.CharField(max_length=400)),
                ('shipox_created_at', models.CharField(max_length=400)),
                ('shipox_last_status_date', models.CharField(max_length=400)),
                ('order_status', models.BooleanField(default=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordercart',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['id', 'user', 'barcode', 'created_at', 'weight', 'price'], name='ordercart_id_43be67_idx')],
>>>>>>> 2d32d04 (full complated uzpost backend)
            },
        ),
    ]
