# Generated by Django 5.0.6 on 2024-12-13 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_remove_ordercart_response_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ordercart',
            name='ordercart_id_43be67_idx',
        ),
        migrations.AddField(
            model_name='ordercart',
            name='archiving_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='ordercart',
            index=models.Index(fields=['id', 'user', 'barcode', 'created_at', 'weight', 'price', 'created_at', 'archiving_status'], name='ordercart_id_063007_idx'),
        ),
    ]
